[package]
name = "HttpClientCLI"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json", "multipart"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"

[profile.release]
opt-level = "z"
lto = true
strip = true